CREATE TABLE PRODUCT(
    ProductId INT,
    ProductName VARCHAR2(30),
    ProductCategory VARCHAR2(30),
    QTY INT,
    CompanyName VARCHAR2(30),
    CONSTRAINT PRODUCT_PK PRIMARY KEY (ProductId) 
);

CREATE TABLE COMPANY(
    CompanyId INT,
    CompanyName VARCHAR2(30),
    CompanyPhoneNumber VARCHAR2(30),
    CompanyAdresse VARCHAR2(30),
    CONSTRAINT COMPANY_PK PRIMARY KEY (CompanyId)
);

CREATE TABLE ORDRE(
    OrderId INT,
    CompanyId INT,
    OrderDate Date,
    CONSTRAINT ORDRE_PK PRIMARY KEY (OrderId)
);

CREATE TABLE PRODUCT_ORDER(
    PRODUCT_ORDERId INT,
    OrderId INT,
    ProductId INT,
    QTY INT,
    CONSTRAINT PRODUCT_ORDER_PK PRIMARY KEY (PRODUCT_ORDERId)
);

ALTER TABLE ORDRE
ADD CONSTRAINT ORDRE_FK FOREIGN KEY (CompanyId) REFERENCES COMPANY(CompanyId);

ALTER TABLE PRODUCT_ORDER
ADD CONSTRAINT PRODUCT_ORDER_FK1 FOREIGN KEY (OrderId) REFERENCES ORDRE(OrderId);
ALTER TABLE PRODUCT_ORDER
ADD CONSTRAINT PRODUCT_ORDER_FK2 FOREIGN KEY (ProductId) REFERENCES PRODUCT(ProductId);


/* login */
CREATE TABLE USERS(
    UserId INT,
    NOM VARCHAR2(30),
    PRENOM VARCHAR2(30),
    USERNAME VARCHAR2(20),
    PASSWORD VARCHAR2(20),
    CONSTRAINT USERS_PK PRIMARY KEY (UserId)
); 

INSERT INTO USERS VALUES(1,'All of Us','ok','admin','admin');




